### ISSUE TITLE
compatibility with Capacitor 6

### ISSUE THREAD

**Issue by G82M** [detchenkov/capacitor-intents#5]
This plugin is currently not compatible with Capacitor 6

Is it possible to upgrade this plugin to Capacitor 6?

Thank you

**Comment by jackywu** [comment]
+1, that's will  be  very helpful.

**Comment by detchenkov** [comment]
@jackywu @G82M Will take a look on weekend

**Comment by detchenkov** [comment]
should be ok on the @next tag : 
npm i capacitor-intents-for-android@next

**Comment by detchenkov** [comment]
Will publish on latest later
